### ISSUE TITLE
First `hatchet install` fails:

### ISSUE THREAD

**Issue by schneems** [heroku/hatchet#85] opened 2020-06-26 15:55 UTC
```
$ be hatchet install
/Users/rschneeman/.gem/ruby/2.7.1/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
/Users/rschneeman/.gem/ruby/2.7.1/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
/Users/rschneeman/.gem/ruby/2.7.1/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
WARNING: add test/fixtures/repos/* to your .gitignore file

bundler: failed to load command: hatchet (/Users/rschneeman/.gem/ruby/2.7.1/bin/hatchet)
RuntimeError: No such file found `hatchet.lock` please run `$ bundle exec hatchet lock`
  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-6.0.0/bin/hatchet:122:in `rescue in load_lockfile'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-6.0.0/bin/hatchet:119:in `load_lockfile'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-6.0.0/bin/hatchet:41:in `install'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-6.0.0/bin/hatchet:179:in `<top (required)>'
  /Users/rschneeman/.gem/ruby/2.7.1/bin/hatchet:23:in `load'
  /Users/rschneeman/.gem/ruby/2.7.1/bin/hatchet:23:in `<top (required)>'
⛄ 2.7.1 🚀  ~/Documents/projects/docker-heroku-ruby-builder (master)
$ bundle exec hatchet lock
/Users/rschneeman/.gem/ruby/2.7.1/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
/Users/rschneeman/.gem/ruby/2.7.1/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
bundler: failed to load command: hatchet (/Users/rschneeman/.gem/ruby/2.7.1/bin/hatchet)
RuntimeError: No such file found `hatchet.lock` please run `$ bundle exec hatchet lock`
  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-6.0.0/bin/hatchet:122:in `rescue in load_lockfile'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-6.0.0/bin/hatchet:119:in `load_lockfile'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-6.0.0/bin/hatchet:70:in `lock'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /Users/rschneeman/.gem/ruby/2.7.1/gems/heroku_hatchet-6.0.0/bin/hatchet:179:in `<top (required)>'
  /Users/rschneeman/.gem/ruby/2.7.1/bin/hatchet:23:in `load'
  /Users/rschneeman/.gem/ruby/2.7.1/bin/hatchet:23:in `<top (required)>'
⛄ 2.7.1 🚀  ~/Documents/projects/docker-heroku-ruby-builder (master)
$ touch hatchet.lock
⛄ 2.7.1 🚀  ~/Documents/projects/docker-heroku-ruby-builder (master)
$ bundle exec hatchet lock
/Users/rschneeman/.gem/ruby/2.7.1/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
/Users/rschneeman/.gem/ruby/2.7.1/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
/Users/rschneeman/.gem/ruby/2.7.1/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
== locking test/fixtures/repos/ruby/default_ruby
Running: cd test/fixtures/repos/ruby/default_ruby/.. && git clone https://github.com/sharpstone/default_ruby.git --quiet
Done!
```

**Comment by Malax** [comment] 2020-08-14 08:16
From #115 (a duplicate of this issue)
> What project did you run into this on?

It was in the [heroku/gradle](https://github.com/heroku/heroku-buildpack-gradle) buildpack. It used hatchet 3.x previously which does not seem to require a lockfile. This is not a huge issue since the workaround is straightforward. I just thought tracking makes sense.

**Closed** 2020-08-20 13:48 UTC
