### ISSUE TITLE
Cannot create `hatchet.lock` without existing `hatchet.lock`

### ISSUE THREAD

**Issue by Malax** [heroku/hatchet#115] opened 2020-08-12 10:23 UTC
`bundle exec hatchet lock` fails when there is no already existing `hatchet.lock`. Creating an empty `hatchet.lock` before executing `bundle exec hatchet lock` can be used as a workaround.

**Comment by schneems** [comment] 2020-08-14 03:27
This is a duplicate of https://github.com/heroku/hatchet/issues/85, let's track it over there. What project did you run into this on?

**Closed by schneems** 2020-08-14 03:27 UTC
